--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Creadores-Program/ViaBedrockDetect
build-by-default: true
branches:
- main
projects:
  ViaBedrockDetect:
    path: Pocketmine/plugin/
...
